# Generated by Django 6.1.1 on 2026-09-28 21:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteBusqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=80, unique=True)),
                ('veces', models.PositiveIntegerField(default=1)),
                ('fecha_ultimo_uso', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Busqueda de cliente',
                'verbose_name_plural': 'Busquedas de clientes',
                'ordering': ['-veces'],
            },
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_negocio', models.CharField(max_length=120, verbose_name='Nombre del negocio')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='negocio/', verbose_name='Logo')),
                ('telefono', models.CharField(blank=True, max_length=40, verbose_name='Telefono')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='Direccion')),
                ('nit', models.CharField(blank=True, max_length=40, verbose_name='NIT')),
                ('mensaje_comprobante', models.CharField(blank=True, help_text='Texto que sale abajo en el comprobante de pago.', max_length=300, verbose_name='Mensaje del comprobante')),
                ('moneda_simbolo', models.CharField(default='$', max_length=8, verbose_name='Simbolo de la moneda')),
                ('moneda_codigo', models.CharField(default='COP', max_length=8, verbose_name='Codigo de la moneda')),
                ('moneda_decimales', models.PositiveSmallIntegerField(default=0, verbose_name='Decimales')),
                ('formato_fecha', models.CharField(default='%d/%m/%Y', max_length=20, verbose_name='Formato de fecha')),
                ('umbral_excelente', models.PositiveSmallIntegerField(default=90, help_text='Porcentaje de pagos puntuales para estar en categoria EXCELENTE.', verbose_name='Umbral EXCELENTE (%)')),
                ('umbral_bueno', models.PositiveSmallIntegerField(default=70, help_text='Porcentaje de pagos puntuales para estar en categoria BUENO.', verbose_name='Umbral BUENO (%)')),
                ('dias_para_moroso', models.PositiveSmallIntegerField(default=15, help_text='Dias de atraso de la cuota mas vieja para marcar como MOROSO.', verbose_name='Dias para MOROSO')),
                ('dias_gracia', models.PositiveSmallIntegerField(default=0, help_text='Dias de tolerancia despues del vencimiento para que el pago siga contando como puntual (0 = puntual solo si pago a tiempo).', verbose_name='Dias de gracia')),
                ('minimo_cuotas_para_clasificar', models.PositiveSmallIntegerField(default=1, help_text='Con menos cuotas pagadas que esto el cliente sale como SIN DATOS.', verbose_name='Minimo de cuotas para clasificar')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracion del sistema',
                'verbose_name_plural': 'Configuracion del sistema',
            },
        ),
        migrations.CreateModel(
            name='FrecuenciaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True, verbose_name='Nombre')),
                ('dias', models.PositiveIntegerField(default=30, verbose_name='Dias de intervalo')),
                ('unidad', models.CharField(choices=[('DIAS', 'Dias'), ('MESES', 'Meses')], default='DIAS', help_text='Dias = suma exacta de dias. Meses = suma meses de calendario (mejor para el pago mensual).', max_length=6, verbose_name='Unidad')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveSmallIntegerField(default=100, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Frecuencia de pago',
                'verbose_name_plural': 'Frecuencias de pago',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveSmallIntegerField(default=100, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Metodo de pago',
                'verbose_name_plural': 'Metodos de pago',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Producto')),
                ('marca', models.CharField(blank=True, max_length=80, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=80, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=80, verbose_name='Numero de serie')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('precio_contado', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Precio de contado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ReglaRegularidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('EXCELENTE', 'Excelente'), ('BUENO', 'Bueno'), ('IRREGULAR', 'Irregular'), ('ATRASADO', 'Atrasado'), ('MOROSO', 'Moroso')], max_length=12, unique=True)),
                ('porcentaje_minimo', models.PositiveSmallIntegerField(default=0, verbose_name='Puntualidad minima (%)')),
                ('max_cuotas_vencidas', models.PositiveSmallIntegerField(default=999, verbose_name='Maximo de cuotas vencidas')),
                ('max_dias_atraso', models.PositiveSmallIntegerField(default=999, verbose_name='Maximo de dias de atraso')),
                ('color', models.CharField(default='#22c55e', max_length=9, verbose_name='Color de la barra')),
                ('orden', models.PositiveSmallIntegerField(default=100, verbose_name='Orden')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Regla de regularidad',
                'verbose_name_plural': 'Reglas de regularidad',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=80, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=80, verbose_name='Apellidos')),
                ('cedula', models.CharField(help_text='Sin puntos ni guiones. Ejemplo: 123456789', max_length=30, unique=True, verbose_name='Numero de cedula')),
                ('telefono', models.CharField(max_length=40, verbose_name='Telefono principal')),
                ('telefono_alternativo', models.CharField(blank=True, max_length=40, verbose_name='Telefono alterno')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion')),
                ('ciudad', models.CharField(max_length=80, verbose_name='Ciudad')),
                ('barrio', models.CharField(blank=True, max_length=80, verbose_name='Barrio')),
                ('referencia_nombre', models.CharField(blank=True, max_length=120, verbose_name='Nombre de la referencia')),
                ('referencia_telefono', models.CharField(blank=True, max_length=40, verbose_name='Telefono de la referencia')),
                ('ocupacion', models.CharField(blank=True, max_length=120, verbose_name='Ocupacion')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, help_text='Desactive para que no aparezca en las listas de cobranza. No se borra nada: sus creditos y pagos se conservan.', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Ultima modificacion')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_texto', models.CharField(blank=True, help_text='Se llena solo si el producto no esta en el catalogo.', max_length=200, verbose_name='Producto (escrito)')),
                ('fecha_venta', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de la venta')),
                ('precio_contado', models.DecimalField(decimal_places=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Precio de contado')),
                ('precio_financiado', models.DecimalField(decimal_places=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Precio financiado (total con cuota inicial)')),
                ('cuota_inicial', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Cuota inicial (abono)')),
                ('valor_financiado', models.DecimalField(decimal_places=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Saldo a financiar')),
                ('valor_cuota', models.DecimalField(decimal_places=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor de cada cuota')),
                ('numero_cuotas', models.PositiveIntegerField(verbose_name='Numero de cuotas')),
                ('fecha_primera_cuota', models.DateField(verbose_name='Fecha de la primera cuota')),
                ('fecha_estimada_fin', models.DateField(verbose_name='Fecha estimada de finalizacion')),
                ('fecha_finalizacion', models.DateField(blank=True, null=True, verbose_name='Fecha real de finalizacion')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo (saldo pendiente)'), ('PAGADO', 'Pagado (cancelado)'), ('ANULADO', 'Anulado')], default='ACTIVO', max_length=10, verbose_name='Estado')),
                ('total_pagado', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=14, verbose_name='Total pagado')),
                ('saldo', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=14, verbose_name='Saldo pendiente')),
                ('cuotas_pagadas', models.PositiveIntegerField(default=0, verbose_name='Cuotas pagadas')),
                ('cuotas_vencidas', models.PositiveIntegerField(default=0, verbose_name='Cuotas vencidas')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creditos', to='cartera.cliente', verbose_name='Cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('frecuencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creditos', to='cartera.frecuenciapago', verbose_name='Frecuencia de pago')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creditos', to='cartera.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Credito',
                'verbose_name_plural': 'Creditos',
                'ordering': ['-fecha_venta', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Numero de cuota')),
                ('fecha_vencimiento', models.DateField(db_index=True, verbose_name='Fecha de vencimiento')),
                ('valor', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Valor de la cuota')),
                ('valor_pagado', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=14, verbose_name='Abonado')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcial'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida')], default='PENDIENTE', max_length=10, verbose_name='Estado guardado')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha en que se termino de pagar')),
                ('fecha_ultimo_abono', models.DateField(blank=True, null=True, verbose_name='Fecha del ultimo abono')),
                ('observacion', models.CharField(blank=True, max_length=200)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='cartera.credito', verbose_name='Credito')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'ordering': ['credito', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FRONTAL', 'Frente de la cedula'), ('POSTERIOR', 'Reverso de la cedula'), ('OTRO', 'Otro documento')], max_length=12, verbose_name='Tipo')),
                ('archivo', models.ImageField(upload_to='cedula/%Y/%m/', verbose_name='Foto')),
                ('nombre_original', models.CharField(blank=True, max_length=200)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='cartera.cliente', verbose_name='Cliente')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento del cliente',
                'verbose_name_plural': 'Documentos de clientes',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='HistorialMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha')),
                ('tipo', models.CharField(choices=[('CLIENTE', 'Cliente'), ('CREDITO', 'Credito'), ('CUOTA', 'Cuota'), ('PAGO', 'Pago'), ('ANULACION', 'Anulacion de pago'), ('USUARIO', 'Usuario'), ('CONFIG', 'Configuracion'), ('RESPALDO', 'Respaldo'), ('INGRESO', 'Ingreso al sistema')], max_length=12, verbose_name='Tipo')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripcion')),
                ('datos', models.JSONField(blank=True, default=dict, verbose_name='Datos del cambio')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='cartera.cliente', verbose_name='Cliente')),
                ('credito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='cartera.credito', verbose_name='Credito')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Movimiento del historial',
                'verbose_name_plural': 'Historial de movimientos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Fecha del pago')),
                ('hora', models.TimeField(default=django.utils.timezone.localtime, verbose_name='Hora del pago')),
                ('valor', models.DecimalField(decimal_places=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Valor pagado')),
                ('referencia', models.CharField(blank=True, max_length=80, verbose_name='Referencia / No. transaccion')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('anulado', models.BooleanField(default=False, verbose_name='Anulado')),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de anulacion')),
                ('motivo_anulacion', models.CharField(blank=True, max_length=300)),
                ('saldo_antes', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Saldo antes del pago')),
                ('saldo_despues', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Saldo despues del pago')),
                ('recibo', models.CharField(max_length=20, unique=True, verbose_name='Numero de comprobante')),
                ('token', models.CharField(db_index=True, help_text='Sirve para que un pago no se registre dos veces.', max_length=40, unique=True, verbose_name='Identificador unico')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_anulados', to=settings.AUTH_USER_MODEL, verbose_name='Anulado por')),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='cartera.credito', verbose_name='Credito')),
                ('cuota', models.ForeignKey(blank=True, help_text='Vacio cuando el pago se aplico a cuotas que aun no habian llegado (pago anticipado).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='cartera.cuota', verbose_name='Cuota a la que se aplico')),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='cartera.metodopago', verbose_name='Metodo de pago')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha', '-hora', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('COBRA', 'Cobrador')], default='COBRA', max_length=10, verbose_name='Rol')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('telefono', models.CharField(blank=True, max_length=40, verbose_name='Telefono')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
            },
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['cedula'], name='idx_cliente_cedula'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['apellidos', 'nombres'], name='idx_cliente_nombre'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['activo'], name='idx_cliente_activo'),
        ),
        migrations.AddIndex(
            model_name='cuota',
            index=models.Index(fields=['fecha_vencimiento', 'estado'], name='idx_cuota_fec_est'),
        ),
        migrations.AddIndex(
            model_name='cuota',
            index=models.Index(fields=['credito', 'estado'], name='idx_cuota_cred_est'),
        ),
        migrations.AddConstraint(
            model_name='cuota',
            constraint=models.UniqueConstraint(fields=('credito', 'numero'), name='una_cuota_por_numero_en_credito'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['credito', 'fecha'], name='idx_pago_cred_fec'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['anulado'], name='idx_pago_anulado'),
        ),
        migrations.AddIndex(
            model_name='credito',
            index=models.Index(fields=['cliente', 'estado'], name='idx_credito_cli_est'),
        ),
        migrations.AddIndex(
            model_name='credito',
            index=models.Index(fields=['estado'], name='idx_credito_estado'),
        ),
    ]
