# Generated by Django 6.1.1 on 2026-09-28 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='cuota',
            field=models.ForeignKey(blank=True, help_text='La primera cuota que recibio el pago. Para ver como se repartio el resto, mire las Aplicaciones de pago.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='cartera.cuota', verbose_name='Cuota principal'),
        ),
        migrations.CreateModel(
            name='AplicacionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Valor aplicado en esta cuota')),
                ('fecha_aplicacion', models.DateField(verbose_name='Fecha de aplicacion')),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='cartera.cuota', verbose_name='Cuota')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='cartera.pago', verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Aplicacion de pago',
                'verbose_name_plural': 'Aplicaciones de pago',
                'ordering': ['cuota__numero'],
            },
        ),
    ]
