# Generated by Django 6.1.1 on 2026-09-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0002_alter_pago_cuota_aplicacionpago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='fecha_estimada_fin',
            field=models.DateField(blank=True, help_text='Se calcula sola con la frecuencia y el numero de cuotas.', null=True, verbose_name='Fecha estimada de finalizacion'),
        ),
    ]
